version: '3.1'

services:

  convoy-mariadb-columnstore:
    image: mariadb/columnstore
    restart: always
    ports:
     - 3306:3306
    volumes: 
        - "./var-lib-mysql:/var/lib/mysql"
        - "./var-lib-columnstore:/var/lib/columnstore"
        - "./etc-columnstore:/etc/columnstore"

